---
title: "GWAS Notebook for Cassava populations"
authors:
- "Vianey Barrera-Enriquez"
- "Camilo E. Sanchez"
output: html_notebook
---



# Loading functions

```{r}
rpath <- "./R code/"
lapply(list.files(rpath, pattern = "\\.R$", full.names = T), source)
```


# 1. Quality control

```{r}
#

```


# 2. Population structure and covariable selection

```{r}
#

```


# 3. GWAS analysis

```{r}
# 
phenofile <- 'metabolomic_markers.batch05.csv'
wdir <- paste(dir,"/Results_Batch_05/", sep = '')
output <- "CM8996.batch05"
```

```{r message = T, warning = F}
# 
GAPIT3(phenofile, genofile, wdir, trait_list = NULL)
```


# 4. Annotation of results

```{r}
# 
gff3 <- file.choose()
```

```{r}
# 
annotationFile <- file.choose()
```

```{r}
# 
wdir <- paste(dir, "/Results_Batch_05/", sep = '')
output <- "CM8996.batch05"
```

```{r message = T, warning = F}
# 
annotation(Mdir = wdir, 
           output = output, 
           gff3 = gff3, 
           annotationFile = annotationFile)
```


# 5. Boxplots: Genotype vs Phenotype

```{r}
# 
phenofile <- 'metabolomic_markers.batch02.csv'
wdir <- paste(dir,"/Results_Boxplot/", sep = '')
outputname <- "AM1588_metabolomic_data.batch02.boxplot"

```

```{r}
#
snp_list_file <- file.choose()
```

```{r}
# 
labelfile <- file.choose()
```

```{r message = T, warning = F}
# 
GWAS_Boxplot(outputname = outputname, 
             dir = wdir, 
             phenofile, 
             genofile, 
             snp_list_file, 
             labelfile)
```

# 6. Manhattan plots

```{r}
# 

```

